# setup.ps1 — install deps and create Windows start scripts
$ErrorActionPreference = "Stop"

Write-Host "========================================"
Write-Host "  NotebookLM - Setup (Windows)"
Write-Host "========================================"
Write-Host ""

function Assert-Command($name) {
    if (-not (Get-Command $name -ErrorAction SilentlyContinue)) {
        throw "ERROR: $name is required."
    }
}

Assert-Command python
Assert-Command node
Assert-Command npm

Write-Host "python $(python --version 2>&1)"
Write-Host "node   $(node --version)"
Write-Host "npm    $(npm --version)"
Write-Host ""

$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $Root

Write-Host "-- Installing Python package (editable) --"
pip install -e . -q
if (Test-Path "backend/requirements.txt") {
    pip install -r backend/requirements.txt -q
}
Write-Host "OK: Python package"
Write-Host ""

Write-Host "-- Installing frontend dependencies --"
Set-Location (Join-Path $Root "frontend")
npm install --silent
Write-Host "OK: Frontend"
Set-Location $Root
Write-Host ""

@'
# Generated by setup.ps1
Set-Location $PSScriptRoot
Write-Host "Starting NotebookLM API on http://localhost:8000 ..."
python -m notebooklm app run
'@ | Set-Content -Encoding utf8 (Join-Path $Root "start-backend.ps1")

@'
# Generated by setup.ps1
Set-Location (Join-Path $PSScriptRoot "frontend")
Write-Host "Starting frontend on http://localhost:3000 ..."
npx vite --host 0.0.0.0 --port 3000
'@ | Set-Content -Encoding utf8 (Join-Path $Root "start-frontend.ps1")

@'
# Generated by setup.ps1 — starts backend + frontend
$Root = $PSScriptRoot
Write-Host "Starting NotebookLM (backend + frontend) ..."

$backend = Start-Process -FilePath "powershell" -ArgumentList @(
    "-NoProfile", "-ExecutionPolicy", "Bypass",
    "-File", (Join-Path $Root "start-backend.ps1")
) -PassThru -WindowStyle Minimized

try {
    & (Join-Path $Root "start-frontend.ps1")
}
finally {
    if ($backend -and -not $backend.HasExited) {
        Stop-Process -Id $backend.Id -Force -ErrorAction SilentlyContinue
    }
}
'@ | Set-Content -Encoding utf8 (Join-Path $Root "start-all.ps1")

Write-Host "Created start-backend.ps1 / start-frontend.ps1 / start-all.ps1"
Write-Host ""
Write-Host "Quick start:"
Write-Host "  1. Copy .env.example -> .env and set OLLAMA_API_KEY / OPENAI_API_KEY"
Write-Host "     VLLM_BASE_URL=https://ollama.com/v1"
Write-Host "     DEFAULT_MODEL=gpt-oss:20b"
Write-Host "  2. .\start-all.ps1"
Write-Host "  3. Open http://localhost:3000"
Write-Host ""
Write-Host "CLI demo:"
Write-Host "  notebooklm interpret backend/examples/research_agent.wfl --input task='...'"
Write-Host ""
